##
## key-generator chart configuration
##

image:
  repository: akirill0v/key_generator
  tag: v0.1.0

replicaCount: 1
## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
## example: helm template charts/kubedb \
##            --set imagePullSecrets[0]=abc \
##            --set imagePullSecrets[1]=xyz
imagePullSecrets: []

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

## Annotations passed to operator pod(s).
##
annotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources:
  requests:
    cpu: 100m
    memory: 100Mi

controller:
  port: 8080
  configPath: /etc/k8s_config/
  configName: default.yaml

config:
  debug: true
  annotation: rsa.customer.keys/service
  rsa:
    bits: 2048
  secrets:
    public_name: public-rsa-tokens
  volumes:
    mount: true
    public:
      path: /var/keys/public
    private:
      path: /var/keys/private
