{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "key_generator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "key_generator.labels" . | nindent 4 }}
imagePullSecrets:
  {{- range $x := .Values.imagePullSecrets }}
  - name: "{{ $x }}"
  {{- end }}
{{ end }}
