---
debug: true
annotation: rsa.customer.keys/service
rsa:
  bits: 2048
secrets:
  public_name: public-rsa-tokens
  public_namespaces:
    - staging
    - default
    - kube-system
volumes:
  mount: true
  public:
    path: /var/keys/public
  private:
    path: /var/keys/private
