---
debug: true
annotation: career.evrone.com/service
rsa:
  bits: 2048
secrets:
  public_name: public-rsa-tokens
volumes:
  mount: true
  public:
    path: /var/keys/public
  private:
    path: /var/keys/private
